import { prisma } from "../src/lib/prisma";

async function main() {
  console.log("Updating St. John Samaritan template to Portrait...");

  const jsonData = {
    elements: [
      {
        id: "bg-top",
        type: "rectangle",
        name: "Top Blue Background",
        x: 0,
        y: 0,
        width: 638,
        height: 380,
        fill: "#2E58A6",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 0,
      },
      {
        id: "estd-text",
        type: "text",
        name: "ESTD Text",
        text: "ESTD 2001",
        x: 30,
        y: 25,
        width: 150,
        height: 30,
        fontFamily: "Inter",
        fontSize: 16,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 1,
      },
      {
        id: "logo",
        type: "image",
        name: "School Logo",
        url: "/images/st-john-logo.png",
        x: 264,
        y: 20,
        width: 110,
        height: 110,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 2,
      },
      {
        id: "his-grace",
        type: "text",
        name: "His Grace",
        text: "H†S GRACE",
        x: 0,
        y: 140,
        width: 638,
        height: 30,
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 3,
      },
      {
        id: "quote",
        type: "text",
        name: "Quote",
        text: "\"Fear of the Lord is the beginning of the wisdom\"",
        x: 0,
        y: 165,
        width: 638,
        height: 30,
        fontFamily: "Inter",
        fontSize: 16,
        fontWeight: "normal",
        fontStyle: "italic",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 4,
      },
      {
        id: "school-name",
        type: "text",
        name: "School Name",
        text: "ST.JOHN SAMARITAN",
        x: 0,
        y: 190,
        width: 638,
        height: 50,
        fontFamily: "Arial Black",
        fontSize: 44,
        fontWeight: "bolder",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 5,
      },
      {
        id: "school-subtitle",
        type: "text",
        name: "School Subtitle",
        text: "ENGLISH MEDIUM PRIMARY & HIGH SCHOOL",
        x: 0,
        y: 245,
        width: 638,
        height: 30,
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 6,
      },
      {
        id: "separator-line",
        type: "rectangle",
        name: "White Line",
        x: 40,
        y: 285,
        width: 558,
        height: 2,
        fill: "#FFFFFF",
        rotation: 0,
        opacity: 0.6,
        visible: true,
        locked: true,
        layerIndex: 7,
      },
      {
        id: "address",
        type: "text",
        name: "Address",
        text: "BAPUJI COLONY ANAND NAGAR OLD HUBLI-HUBBALLI\nOFFICE CONTACT NO - (M) 9480133117",
        x: 0,
        y: 295,
        width: 638,
        height: 60,
        fontFamily: "Inter",
        fontSize: 15,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 8,
      },
      {
        id: "title",
        type: "text",
        name: "ID Card Title",
        text: "ID CARD 2026-27",
        x: 0,
        y: 395,
        width: 638,
        height: 40,
        fontFamily: "Arial Black",
        fontSize: 32,
        fontWeight: "bolder",
        fontStyle: "normal",
        textColor: "#D91C1C",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 9,
      },
      {
        id: "label-name",
        type: "text",
        name: "Label Name",
        text: "NAME:",
        x: 30,
        y: 450,
        width: 100,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 10,
      },
      {
        id: "value-name",
        type: "placeholder",
        placeholderType: "student_name",
        name: "Student Name",
        x: 130,
        y: 450,
        width: 450,
        height: 30,
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "bold",
        textColor: "#D91C1C",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 11,
      },
      {
        id: "label-father",
        type: "text",
        name: "Label Father",
        text: "FATHER NAME:",
        x: 30,
        y: 500,
        width: 190,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 12,
      },
      {
        id: "value-father",
        type: "placeholder",
        placeholderType: "father_name",
        name: "Father Name",
        x: 220,
        y: 500,
        width: 400,
        height: 30,
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "bold",
        textColor: "#2E58A6",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 13,
      },
      {
        id: "label-class",
        type: "text",
        name: "Label Class",
        text: "CLASS:",
        x: 30,
        y: 550,
        width: 100,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 14,
      },
      {
        id: "value-class",
        type: "placeholder",
        placeholderType: "class_name",
        name: "Class Value",
        x: 130,
        y: 550,
        width: 150,
        height: 30,
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "bold",
        textColor: "#D91C1C",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 15,
      },
      {
        id: "label-dob",
        type: "text",
        name: "Label DOB",
        text: "DOB:",
        x: 300,
        y: 550,
        width: 70,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 16,
      },
      {
        id: "value-dob",
        type: "placeholder",
        placeholderType: "dob",
        name: "DOB Value",
        x: 370,
        y: 550,
        width: 200,
        height: 30,
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "bold",
        textColor: "#D91C1C",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 17,
      },
      {
        id: "label-mobile",
        type: "text",
        name: "Label Mobile",
        text: "MOBILE:",
        x: 30,
        y: 600,
        width: 120,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 18,
      },
      {
        id: "value-mobile",
        type: "placeholder",
        placeholderType: "student_mobile",
        name: "Mobile Value",
        x: 150,
        y: 600,
        width: 400,
        height: 30,
        fontFamily: "Inter",
        fontSize: 24,
        fontWeight: "bold",
        textColor: "#D91C1C",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 19,
      },
      {
        id: "label-address",
        type: "text",
        name: "Label Address",
        text: "ADDRESS:",
        x: 30,
        y: 650,
        width: 140,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 20,
      },
      {
        id: "value-address",
        type: "placeholder",
        placeholderType: "address",
        name: "Address Value",
        x: 170,
        y: 650,
        width: 430,
        height: 60,
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        textColor: "#D91C1C",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 21,
      },
      {
        id: "student-photo",
        type: "placeholder",
        placeholderType: "student_photo",
        name: "Student Photo",
        x: 30,
        y: 700,
        width: 220,
        height: 280,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 22,
      },
      {
        id: "principal-sign",
        type: "image",
        name: "Principal Signature",
        url: "/images/principal-sign.png",
        x: 418,
        y: 870,
        width: 180,
        height: 70,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 23,
      },
      {
        id: "label-sign",
        type: "text",
        name: "Principal Sign Label",
        text: "Principal Sign",
        x: 418,
        y: 945,
        width: 180,
        height: 30,
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "center",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 24,
      }
    ],
    background: "#FFFFFF"
  };

  // Update ALL templates that match this name to have the new layout
  const templates = await prisma.template.findMany({
    where: { name: "St. John Samaritan ID" }
  });

  for (const template of templates) {
    await prisma.template.update({
      where: { id: template.id },
      data: {
        orientation: "portrait",
        width: 54,
        height: 86,
        canvasWidth: 638,
        canvasHeight: 1016,
      }
    });

    // Create a new version for it
    const newVersion = await prisma.templateVersion.create({
      data: {
        templateId: template.id,
        version: 2, // integer
        versionName: "Portrait Update",
        jsonData: jsonData,
        published: true,
        createdBy: "system",
      }
    });

    // Update current version pointer
    await prisma.template.update({
      where: { id: template.id },
      data: { currentVersionId: newVersion.id }
    });
  }

  console.log("Updated", templates.length, "templates to Portrait.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
