import { prisma } from "../src/lib/prisma";

async function main() {
  console.log("Seeding St. John Samaritan template...");

  const jsonData = {
    elements: [
      {
        id: "bg-top",
        type: "rectangle",
        name: "Top Blue Background",
        x: 0,
        y: 0,
        width: 1016,
        height: 260,
        fill: "#1A56DB",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 0,
      },
      {
        id: "bg-bottom",
        type: "rectangle",
        name: "Bottom Blue Background",
        x: 0,
        y: 600,
        width: 1016,
        height: 38,
        fill: "#1A56DB",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 1,
      },
      {
        id: "bg-curve",
        type: "circle",
        name: "Left Blue Curve",
        x: -400,
        y: -100,
        width: 500,
        height: 1000,
        fill: "#1A56DB",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 2,
      },
      {
        id: "logo",
        type: "image",
        name: "School Logo",
        url: "/images/st-john-logo.png",
        x: 20,
        y: 30,
        width: 350,
        height: 230,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 3,
      },
      {
        id: "estd-text",
        type: "text",
        name: "ESTD Text",
        text: "ESTD:2001",
        x: 20,
        y: 20,
        width: 350,
        height: 30,
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 4,
      },
      {
        id: "his-grace",
        type: "text",
        name: "His Grace",
        text: "HIS GRACE",
        x: 380,
        y: 20,
        width: 616,
        height: 30,
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 5,
      },
      {
        id: "quote",
        type: "text",
        name: "Quote",
        text: "\"Fear of the Lord is the beginning of wisdom\"",
        x: 380,
        y: 45,
        width: 616,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        fontStyle: "italic",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 6,
      },
      {
        id: "school-name",
        type: "text",
        name: "School Name",
        text: "ST.JOHN SAMARITAN",
        x: 380,
        y: 75,
        width: 616,
        height: 70,
        fontFamily: "Inter",
        fontSize: 52,
        fontWeight: "bolder",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 7,
      },
      {
        id: "school-subtitle",
        type: "text",
        name: "School Subtitle",
        text: "ENGLISH MEDIUM PRIMARY & HIGH SCHOOL",
        x: 380,
        y: 135,
        width: 616,
        height: 40,
        fontFamily: "Inter",
        fontSize: 20,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 8,
      },
      {
        id: "separator-line",
        type: "rectangle",
        name: "White Line",
        x: 400,
        y: 175,
        width: 566,
        height: 3,
        fill: "#FFFFFF",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 9,
      },
      {
        id: "address",
        type: "text",
        name: "Address",
        text: "BAPUJI COLONY ANAND NAGAR OLD HUBLI-HUBBALLI",
        x: 380,
        y: 185,
        width: 616,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 10,
      },
      {
        id: "contact",
        type: "text",
        name: "Contact",
        text: "OFFICE CONTACT NO : 9902396096 - 9663868677",
        x: 380,
        y: 215,
        width: 616,
        height: 30,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#FFFFFF",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 11,
      },
      {
        id: "title",
        type: "text",
        name: "ID Card Title",
        text: "ID CARD 2026-27",
        x: 300,
        y: 275,
        width: 450,
        height: 50,
        fontFamily: "Inter",
        fontSize: 42,
        fontWeight: "bolder",
        fontStyle: "normal",
        textColor: "#D91C1C",
        textAlign: "center",
        textTransform: "uppercase",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 12,
      },
      {
        id: "student-photo",
        type: "placeholder",
        placeholderType: "student_photo",
        name: "Student Photo",
        x: 50,
        y: 300,
        width: 220,
        height: 270,
        rotation: 0,
        opacity: 1,
        stroke: "#000000",
        strokeWidth: 6,
        visible: true,
        locked: false,
        layerIndex: 13,
      },
      {
        id: "label-name",
        type: "text",
        name: "Label Name",
        text: "NAME :",
        x: 320,
        y: 340,
        width: 150,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 14,
      },
      {
        id: "value-name",
        type: "placeholder",
        placeholderType: "student_name",
        name: "Student Name",
        x: 450,
        y: 340,
        width: 500,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        textColor: "#000000",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 15,
      },
      {
        id: "label-father",
        type: "text",
        name: "Label Father",
        text: "FATHER NAME :",
        x: 320,
        y: 390,
        width: 220,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 16,
      },
      {
        id: "value-father",
        type: "placeholder",
        placeholderType: "father_name",
        name: "Father Name",
        x: 550,
        y: 390,
        width: 400,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        textColor: "#000000",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 17,
      },
      {
        id: "label-class",
        type: "text",
        name: "Label Class",
        text: "CLASS :",
        x: 320,
        y: 440,
        width: 150,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 18,
      },
      {
        id: "value-class",
        type: "placeholder",
        placeholderType: "class",
        name: "Class Value",
        x: 450,
        y: 440,
        width: 200,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        textColor: "#000000",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 19,
      },
      {
        id: "label-dob",
        type: "text",
        name: "Label DOB",
        text: "DOB :",
        x: 650,
        y: 440,
        width: 100,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 20,
      },
      {
        id: "value-dob",
        type: "placeholder",
        placeholderType: "dob",
        name: "DOB Value",
        x: 750,
        y: 440,
        width: 200,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        textColor: "#000000",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 21,
      },
      {
        id: "label-mobile",
        type: "text",
        name: "Label Mobile",
        text: "MOBILE :",
        x: 320,
        y: 490,
        width: 150,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 22,
      },
      {
        id: "value-mobile",
        type: "placeholder",
        placeholderType: "mobile",
        name: "Mobile Value",
        x: 460,
        y: 490,
        width: 400,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        textColor: "#000000",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 23,
      },
      {
        id: "label-address",
        type: "text",
        name: "Label Address",
        text: "ADDRESS :",
        x: 320,
        y: 540,
        width: 150,
        height: 40,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        textColor: "#000000",
        textAlign: "left",
        textTransform: "none",
        autoResize: false,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        layerIndex: 24,
      },
      {
        id: "value-address",
        type: "placeholder",
        placeholderType: "address",
        name: "Address Value",
        x: 480,
        y: 540,
        width: 300,
        height: 120,
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "normal",
        textColor: "#000000",
        textAlign: "left",
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 25,
      },
      {
        id: "principal-sign",
        type: "image",
        name: "Principal Signature",
        url: "/images/principal-sign.png",
        x: 800,
        y: 490,
        width: 166,
        height: 100,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        layerIndex: 26,
      },

    ],
    background: "#FFFFFF"
  };

  const templates = await prisma.template.findMany({
    where: { name: "St. John Samaritan ID" }
  });

  for (const template of templates) {
    await prisma.template.update({
      where: { id: template.id },
      data: {
        orientation: "landscape",
        width: 86,
        height: 54,
        canvasWidth: 1016,
        canvasHeight: 638,
      }
    });

    const newVersion = await prisma.templateVersion.create({
      data: {
        templateId: template.id,
        version: 1784144784,
        versionName: "Landscape Fixed Logo Update",
        jsonData: jsonData,
        published: true,
        createdBy: "system",
      }
    });

    await prisma.template.update({
      where: { id: template.id },
      data: { currentVersionId: newVersion.id }
    });
  }

  console.log("Updated", templates.length, "templates to Landscape with fixed logos.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
